# Generated by Django 4.2 on 2023-06-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tatu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, verbose_name='')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('tel', models.CharField(default='+7', max_length=100, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='MasterCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('tel', models.CharField(default='+7', max_length=100, verbose_name='Номер телефона')),
                ('chart', models.CharField(default='пн/сб', max_length=100, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Мастера',
                'verbose_name_plural': 'Мастер',
            },
        ),
        migrations.CreateModel(
            name='SupportCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infsys.clientcrm')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infsys.mastercrm')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tatu.serviceprice')),
            ],
            options={
                'verbose_name': 'Записи',
                'verbose_name_plural': 'Запись',
            },
        ),
    ]
