# Generated by Django 4.2 on 2023-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcrm',
            name='name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Имя'),
        ),
    ]
